<?php $PU->emitHtmlBoilerplate("Welcome!", $params); ?>

<h1>Welcome to PHP Template Project!</h1>

<p>This code was generated by PHP Project Initializer.
You probably want to make some modifications.</p>

<p>See also: <a href="<?php echo htmlspecialchars($helloUri); ?>"><?php echo htmlspecialchars($helloUri); ?></a></p>

<h4>Some REST Services</h4>
<ul>
<?php echo implode("\n",$classLinks) ?>
</ul>

<style>
dl.tabby { display: table; }
dl.tabby div { display: table-row; }
dl.tabby dt {
	display: table-cell;
	padding: 2px 8px 2px 4px;
}
dl.tabby dt:after {
	content: ":";
}
dl.tabby dd {
	display: table-cell;
	padding: 2px 4px 2px 8px;
	text-align: right;
}
</style>

<h4>File upload</h4>

<form action="blobs" method="POST" enctype="multipart/form-data">
<input type="file" name="files[]" multiple="multiple">
<input type="submit" name="Go!"/>
</form>

<h4>Other stuff</h4>
<dl class="tabby">
<?php foreach($otherStuff as $thing=>$stuff): ?>
<div><dt><?php eht($thing); ?></dt><dd><?php eht($stuff); ?></dd></div>
<?php endforeach; ?>
</dl>

<ul>
<?php foreach($otherLinks as $title=>$href): ?>
<li><a href="<?php eht($href); ?>"><?php eht($title); ?></a></li>
<?php endforeach; ?>
</ul>

<?php $PU->emitHtmlFooter(); ?>
