#!/usr/bin/env php
<?php

$selfDir = dirname(__DIR__);
require_once "$selfDir/init-environment.php";
require_once "$selfDir/init-error-handling.php";

$MPM = $TFMPM_Registry->mapPreviewManager;

$options = array(
	'beLazy' => false,
	'verbosity' => 0
);
$params = $MPM->parseMapGenerationParamsFromCommandLine($argv, $options);

$MPM->generateMapPreview($params, $options);
