#!/usr/bin/env php
<?php

require_once __DIR__.'/../init-error-handling.php';
$reg = require_once __DIR__.'/../init-environment.php';
$rcs = $reg->schema->getResourceClasses();
$sqlRunner = $reg->sqlRunner;
$insertRows = [];
foreach( $rcs as $rc ) {
	$entityId = $rc->getFirstPropertyValue("http://ns.nuke24.net/Phrebar/entityId");
	if( $entityId !== null ) {
		$insertRows[] = $sqlRunner->quoteParams("({eid}, {name})", ['eid'=>$entityId, 'name'=>$rc->getName()]);
	}
}
echo "DELETE FROM phptemplateprojectdatabasenamespace.resourceclass;\n";
if( count($insertRows) > 0 ) {
	echo "INSERT INTO phptemplateprojectdatabasenamespace.resourceclass\n";
	echo "(id, name) VALUES\n";
	echo implode(",\n", $insertRows), ";\n";
}
