#!/usr/bin/env php
<?php

$reg = require_once __DIR__.'/../init-environment.php';
if( count($argv) == 1 ) {
	fwrite(STDERR, "No passwords specified.  Provide passwords to be hashed as command-line arguments.\n");
}
for( $i=1; $i<count($argv); ++$i ) {
	echo $reg->passwordModel->hashPassword($argv[$i]), "\n";
}
